apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metal3

resources:
  - https://github.com/metal3-io/baremetal-operator//config/use-irso?ref=v0.13.2
  - ironic.yaml

images:
  - name: quay.io/metal3-io/baremetal-operator
    newTag: v0.13.0
