apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: homelab-worker
  namespace: metal3
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            - name: node-labels
              value: 'node-role.kubernetes.io/worker=true,metal3.io/uuid={{ ds.meta_data.uuid }}'
      preKubeadmCommands:
        - apt-get update
        - apt-get install -y ca-certificates curl gpg
        - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.37/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes.gpg
        - echo 'deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.37/deb/ /' > /etc/apt/sources.list.d/kubernetes.list
        - curl -fsSL https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.37/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o.gpg
        - echo 'deb [signed-by=/etc/apt/keyrings/cri-o.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/v1.37/deb/ /' > /etc/apt/sources.list.d/cri-o.list
        - apt-get update
        - apt-get install -y cri-o kubelet kubeadm
        - systemctl enable --now crio
        - systemctl enable kubelet
