apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: homelab-worker
  namespace: metal3
spec:
  clusterName: homelab
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: homelab
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: homelab
    spec:
      clusterName: homelab
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: homelab-worker
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
        name: homelab-worker
      version: v1.36.2
