apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysite
  namespace: argocd
  labels:
    app.kubernetes.io/name: mysite
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/homelab.git
    targetRevision: HEAD
    path: argocd/workloads/services/mysite
  destination:
    server: https://kubernetes.default.svc
    namespace: mysite
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
    retry:
      limit: 10
      backoff: { duration: 30s, factor: 2, maxDuration: 5m }
