apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: srv-03
  namespace: metal3
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "4c:52:62:17:10:ef"
  bmc:
    address: ipmi://172.16.1.13
    credentialsName: bmc-auth
    disableCertificateVerification: true
  rootDeviceHints:
    serialNumber: "19R0A0MDF3NG"
