apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: srv-02
  namespace: metal3
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "4c:52:62:16:8b:9f"
  bmc:
    address: ipmi://172.16.1.12
    credentialsName: bmc-auth
    disableCertificateVerification: true
  rootDeviceHints:
    deviceName: "/dev/sda"
