apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: srv-01
  namespace: metal3
  labels:
    cluster-role: control-plane
spec:
  online: true
  bootMode: UEFI
  bootMACAddress: "4c:52:62:16:33:8d"
  bmc:
    address: ipmi://172.16.1.11
    credentialsName: bmc-auth
    disableCertificateVerification: true
  rootDeviceHints:
    serialNumber: "1960A03GF3NG"
