apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/homelab.git
    targetRevision: HEAD
    path: hardware
  destination:
    server: https://kubernetes.default.svc
    namespace: metal3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: metal3.io
      kind: BareMetalHost
      jsonPointers:
        - /spec/consumerRef
        - /spec/image
        - /spec/userData
        - /spec/architecture
