apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baremetal-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/metal3-io/baremetal-operator.git
    targetRevision: v0.13.2
    path: config/use-irso
    kustomize:
      patches:
        - target:
            kind: ConfigMap
            name: ironic
          patch: |-
            - op: add
              path: /data/IRONIC_NAMESPACE
              value: metal3
  destination:
    server: https://kubernetes.default.svc
    namespace: baremetal-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
