apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: Metal3MachineTemplate
metadata:
  name: homelab-control-plane
  namespace: metal3
spec:
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: homelab-control-plane
      image:
        url: https://cloud-images.ubuntu.com/minimal/releases/resolute/release/ubuntu-26.04-minimal-cloudimg-amd64.img
        checksum: https://cloud-images.ubuntu.com/minimal/releases/resolute/release/SHA256SUMS
        checksumType: sha256
        diskFormat: qcow2
      hostSelector:
        matchLabels:
          cluster-role: control-plane
