apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: Metal3MachineTemplate
metadata:
  name: homelab-control-plane
  namespace: metal3
spec:
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: homelab-control-plane
      image:
        url: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
        checksum: https://cloud.debian.org/images/cloud/bookworm/latest/SHA512SUMS
        checksumType: sha512
        diskFormat: qcow2
      hostSelector:
        matchLabels:
          cluster-role: control-plane
