apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caaph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://github.com/daigo-suhara/homelab.git
    targetRevision: HEAD
    path: argocd/management/manifests/caaph
  destination:
    server: https://kubernetes.default.svc
    namespace: caaph-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
